baseURL = ""
title = "Gokberk Gunes"
#theme = "starter"

[menu]
	[[menu.main]]
		identifier = "home"
		name       = "Home"
		url        = "/"
		weight     = 1
	[[menu.main]]
		identifier = "posts"
		name       = "Posts"
		url        = "/posts"
		weight     = 2
	[[menu.main]]
		name       = "Github"
		# Ref. https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/47
		# Open this in new tab, use ext- prefix in the identifier.
		# This hack has its roots in /layouts/partials/nav.html as
		# {{ if (hasPrefix .Identifier "ext-") }}target="_blank"{{ end }}
		identifier = "ext-github"
		url        = "https://github.com/gokberkgunes"
		weight     = 3
	[[menu.main]]
		name       = "Search Engine"
		identifier = "searx"
		url        = "/searx"
		weight     = 4
	#[[menu.main]]
	#	identifier = "about"
	#	name       = "About"
	#	url        = "/about"
	#	weight     = 4


# Ref. https://gohugo.io/getting-started/configuration-markup
[markup]
	# Syntax highlighting. Docs: https://gohugo.io/functions/highlight/
	[markup.highlight]
		anchorLineNos = false
		codeFences = true # Set.
		guessSyntax = true # Set.

		hl_Lines = ''
		hl_inline = false # Set.
		lineAnchors = ''
		# Show line numbers.
		lineNos = false
		lineNoStart = 1

		lineNumbersInTable = false # Set.
		noClasses = true
		noHl = false
		# Themes: https://xyproto.github.io/splash/docs/longer/index.html
		style = "native"
		tabWidth = 8

	# Markdown convertion settings
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			linkifyProtocol = 'https'
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.parser]
			autoHeadingID = true
			autoHeadingIDType = 'github'
			[markup.goldmark.parser.attribute]
				block = false
				title = true
		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = false
			xhtml = false
	[markup.tableOfContents]
		endLevel = 2
		ordered = false
		startLevel = 1
