baseURL = ""
title = "Gokberk Gunes"
#theme = "starter"

[menu]
	[[menu.main]]
		identifier = "home"
		name       = "Home"
		url        = "/"
		weight     = 1
	[[menu.main]]
		identifier = "posts"
		name       = "Posts"
		url        = "/posts"
		weight     = 2
	[[menu.main]]
		identifier = "github"
		name       = "Github"
		url        = "https://github.com/gokberkgunes"
		weight     = 3
	#[[menu.main]]
	#	identifier = "about"
	#	name       = "About"
	#	url        = "/about"
	#	weight     = 4


# Ref. https://gohugo.io/getting-started/configuration-markup
[markup]
	# Syntax highlighting
	[markup.highlight]
		anchorLineNos = true
		codeFences = true
		guessSyntax = true
		hl_Lines = ''
		hl_inline = false
		lineAnchors = ''
		lineNoStart = 1
		lineNos = true
		lineNumbersInTable = false
		noClasses = true
		noHl = true
		style = "pygments"
		tabWidth = 8
	# Markdown convertion settings
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			linkifyProtocol = 'https'
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.parser]
			autoHeadingID = true
			autoHeadingIDType = 'github'
			[markup.goldmark.parser.attribute]
				block = false
				title = true
		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = false
			xhtml = false
	[markup.tableOfContents]
		endLevel = 2
		ordered = false
		startLevel = 1
